from __future__ import annotations
from dataclasses import dataclass
from math import sqrt
from typing import Any, Dict, Optional

# Regime-specific V_t CSV paths — plain-GBM paths in the `V_smooth` column,
# generated by `data/v_gbm.py generate-all`.
FV_CSV = {
    "calm":     "data/fv_calm.csv",
    "stressed": "data/fv_stressed.csv",
}

# Per-regime σ_v: per-step (1-min) log-return std of V_t. Direct fit on the
# 1-min processed ES front-month MID series (data/v_gbm.py calibrate). MT
# also uses this as its reference 1-min return std — by construction the
# empirical 1-min mid log-return std equals σ_v (that is what σ_v is
# calibrated against), so no separate MT_REF dict is needed.
SIGMA_V = {
    "calm":     0.00029732584831326943,
    "stressed": 0.001822674698246824,
}

V0 = {
    "calm":     2463.125,
    "stressed": 3253.875,
}

# MBP-10 geometric placement-depth — diagnostic only (D20). Live limit-
# order placement uses the calibrated log-normal `depth_mean`.
P_ZI = {
    "calm":     0.5430,
    "stressed": 0.3431,
}

# MM top-of-book quote size (D31). Structural — pinned not calibrated;
# `mm_p_edge` is the calibrated MM dial (D48).
MM_QTY = {
    "calm":     2,
    "stressed": 2,
}

# Uniform `U[1, qty_max]` order-size cap (ODD §Stochasticity). D49 reverted
# (Pareto degraded Hill under our linear-impact LOB matching). Flat 10
# matches the ODD baseline; volume scaling to empirical ES is handled by
# the `VOLUME_LOT` relabeling below, not by per-order qty.
QTY_MAX = {
    "calm":     10,
    "stressed": 10,
}

# D50 — Institutional-lot relabeling. The model treats each `qty` unit as
# one 50-contract institutional ES block. Empirical ES per-minute volume
# is ~2,500 (calm) / ~5,000 (stressed); the model's raw per-minute volume
# at qty_max=10 is ~35 / ~40, ≈50–70× short. Reading one model unit as
# 50 contracts (the typical ES block-trade lot in CME data — Eisler-
# Bouchaud-Kockelkoren 2012 reference distribution) brings reported volume
# into the empirical envelope without changing LOB dynamics, log-returns,
# ACFs or Hill (all invariant under multiplicative qty rescaling).
# Applied only at REPORTING and CAPITAL-RATIO computation, never inside
# the LOB / matching engine.
VOLUME_LOT = 50

# CME E-mini ES futures contract multiplier — $50 per index point. Used in
# capital-ratio / notional computations (Stage 4a). The "USD notional per
# (model qty unit · price point)" is therefore VOLUME_LOT · CONTRACT_USD
# = 50 · 50 = $2,500 per model-qty-point.
CONTRACT_USD = 50.0

# Almgren-Chriss impact coefficients — calibrated from BBO-1m via
# data/impact.py (Hasbrouck 1991 / AC 2000 linear-impact regression).
# NOT currently wired into any agent (AC execution tabled under D10f in
# favour of POV; see ModelParams.mm_pov). Kept here for documentation +
# future re-enable. γ both regimes empirically negative (post-trade price
# reversion dominates at K=30 min, Hasbrouck 1991 / BMP 2002 transient-only
# finding) → floored at 0.
ETA_TEMP = {
    "calm":     1.5094e-4,
    "stressed": 7.0064e-4,
}
GAMMA_PERM = {
    "calm":     0.0,   # raw β_perm = -1.17e-5; transient-only regime
    "stressed": 0.0,   # raw β_perm = -1.38e-4; transient-only regime
}

# ZI rates (zi_alpha limit / zi_mu market / zi_delta cancel) are CALIBRATED
# per regime (D21 — all three entered the loop when the MM was dropped and
# ZI became a primary price driver). The ODD-baseline values (0.15 / 0.025 /
# 0.025) are the ModelParams defaults and the calibration-bound anchors.

# Pin point for FT belief dispersion: σ_fundamental = ft_sigma_c · σ_v · v0
# = one daily V_t std (Chiarella heterogeneous-beliefs at the daily-news
# scale; ABIDES ValueAgent precedent). Calibrating ft_sigma_c was tried and
# landed near √(390·5) (one weekly std); the structural pin removes a
# calibrated parameter at negligible cost (FT belief dispersion is a design
# choice, not a market observable).
FT_SIGMA_C_DEFAULT = sqrt(390.0)

# Calibrated behavioural parameters — the 6-d theta per regime (D18b/D18c/D48):
# depth_mean, depth_sigma, zi_alpha, zi_mu, zi_delta, mm_p_edge. Copied from
# `results[regime].theta_stage2` in output/calibrated_params.json. RE-COPY
# after any re-calibration — this dict is the single source the simulator entry
# points (run_simulation.py, analysis_long_run.py) read from.
#
# STALE — both entries below are PRE-D48 placeholders and do NOT match a
# current-model validated run:
#   - stressed: the validated D48 theta (D=21.67) IS in
#     output/calibrated_params.json but was NEVER copied here — copy it back
#     (note the rails: depth_sigma -> 0.95, mm_p_edge -> 1.43).
#   - calm: never run at 6-d (absent from the JSON — a stressed-only run
#     overwrote it). mm_p_edge=4.0 is the D31 default; the rest is the pre-D48
#     5-d overnight stage-2 theta.
CALIBRATED = {
    "calm": dict(
        depth_mean=5.714897, depth_sigma=0.3,
        zi_alpha=0.472154, zi_mu=0.037421, zi_delta=0.361801,
        mm_p_edge=4.0,
    ),
    "stressed": dict(
        depth_mean=7.873318, depth_sigma=0.3,
        zi_alpha=0.495703, zi_mu=0.061506, zi_delta=0.079857,
        mm_p_edge=4.0,
    ),
}


# ── Clearing-tier constants (D28) ────────────────────────────────────────────
# Clearing-member initialisation (ODD §Initialization). Cash is inert (it
# does not gate FT/BCM order submission), so the regulatory-scale BCM/NBCM
# cash does not affect price formation or the calibration.
CCP_CASH = 10_000_000               # ODD MatchingEngine cash
BCM_CASH_RANGE = (5e9, 1e10)        # ODD BankingClearingMember:    U[5B, 10B]
NBCM_CASH_RANGE = (5e6, 1e7)        # ODD NonBankingClearingMember: U[5M, 10M]

# CCP / clearing-tier calibration — ODD §Calibration table. These pin the
# margin, default-fund and waterfall mechanics built in the LATER stages;
# none is a free (SMM-calibrated) parameter — each is a regulatory / ODD
# constant. Listed here as the single source; wired in stage by stage.
CCP_CALIBRATION = dict(
    im_percent=0.20,        # initial margin — LCH/Eurex rulebooks; EMIR Art. 41
    mm_percent=0.95,        # maintenance-margin threshold — CME methodology
    df_percent=0.20,        # DF stress-scenario loss — cover-2 EMIR/CPMI-IOSCO
    ex_df_ratio=0.10,       # exchange skin-in-the-game — EMIR Art. 45
    cover_number=2,         # cover-2 — EMIR / Dodd-Frank
    recovery_rate=0.60,     # auctioned-position recovery — CPMI-IOSCO 2017
    cap_ratio_floor=0.08,   # capital-adequacy floor — Basel III (ODD §Mech #2)
    margin_interval=60,     # variation-margin cadence (hourly) — ODD §Scales
    df_interval=390,        # default-fund recalculation — one thesis RTH day
)                           # (ODD uses 510; the thesis RTH day is 390 — D28)


@dataclass
class ModelParams:
    # ── Populations (54 LOB + clearing tier) ──────────────────────────────
    n_fundamental: int
    n_momentum: int            # MT short-horizon (per-agent λ = params.mt_lambda)
    n_mm: int                  # 4 HFABM mid-anchored MMs (D48)
    n_zi: int                  # ZI background flow (Cont-Stoikov 2008)

    # ── Asset / cadence ──────────────────────────────────────────────────
    v0: float
    tick_size: float
    dt_minutes: float          # 1.0 — 1-min ODD-native cadence

    # ── FT (ODD §Agents) ─────────────────────────────────────────────────
    # Replace-on-new (D5d); trades every step (D36 — `ft_alpha=1.0` pinned).
    # No dead-band — persistent z_score supplies heterogeneity. σ_t reaches
    # the LOB via the FT belief width (D34: σ_fund_t = √390·σ_t·v0).
    ft_alpha: float = 1.0
    ft_sigma_c: float = FT_SIGMA_C_DEFAULT

    # ── ZI (Cont-Stoikov 2008) — three Bernoulli rates per step, all CALIBRATED.
    zi_alpha: float = 0.15     # limit-order arrival
    zi_mu: float = 0.025       # market-order arrival
    zi_delta: float = 0.025    # per-resting cancellation

    # ── Order TTL hard ceiling (D5d, ODD §Mech #7) — every order expires
    # after `order_ttl` steps regardless of agent. ≈10 min at 1-min cadence.
    order_ttl: int = 10

    # ── MT (single-cohort EWMA chartist, D13f / D44) ──────────────────────
    # Limit-only (D40). Replace-on-new (D5d). EWMA decay per-agent at init
    # (params.mt_lambda); placement k ~ shared LogNormal `_draw_depth`.
    mt_alpha: float = 1.0         # trades every step (D36)
    mt_mu: float = 0.0            # market branch off (D40)
    mt_lambda: float = 0.05       # EWMA decay — pinned (D44)
    mt_lambda_long: float = 0.02  # long-cohort decay (D35); n_momentum_long=0 by default
    n_momentum_long: int = 0      # D43 long cohort dropped
    mt_eps: float = 1e-6          # |M_t| floor — skips EWMA warm-up

    # ── Parked agent params (kept for back-compat; cohorts not active) ───
    vt_qty_base: float = 2.0      # VolatilityTrader (D38, removed D44)
    ct_update_prob: float = 0.05  # ContTrader (D39, removed D44)
    ct_qty: float = 1.0

    # ── Limit-order placement depth (shared ZI + MT) ─────────────────────
    # GEOMETRIC k ~ Geometric(p_zi), data-fit p_zi from MBP-10 (Cont-Stoikov-
    # Talreja 2008; reverts the D20 log-normal back to the D3 geometric). Dense
    # at the mid (mode k=1) → thick near-mid book → market orders don't walk a
    # sparse book (the kurtosis-amplification fix). p_zi is data-fixed, NOT in
    # the agent loop. depth_mean/depth_sigma parked for back-compat (unused).
    p_zi: Optional[float] = None  # geometric placement param; populated from P_ZI
    depth_sigma: float = 0.3      # parked (log-normal shape — superseded)
    depth_mean: float = 2.5       # parked (log-normal mean — superseded)

    # ── Stage-4+ fire-sale scaffolding (NOT yet wired) ───────────────────
    # POV execution helpers for the deferred BCM/CCP distressed liquidation
    # (Almgren-Thum-Hauptmann-Li 2005). `ac_schedule()` in agents.py + the
    # ETA_TEMP / GAMMA_PERM dicts above carry over directly when wired.
    mm_pov: float = 0.10
    mm_inventory_limit: int = 1000
    mm_inventory_safe: int = 800      # Stage 4+: post-fire-sale target

    # ── MM (fundamental-anchored inventory-skewed quoting — D10g) ────────
    # `mm_qty` regime-derived from MM_QTY dict (top-of-book passive size,
    # structural). `mm_skew` is the inventory-skew coefficient in the MM
    # reservation r = V_t − mm_skew·inventory·tick (Avellaneda-Stoikov
    # 2008). STRUCTURAL — not calibrated (D10c upheld); it has no traction
    # on the return moments (the V_t anchor pins the mid regardless), its
    # only role is bounding MM inventory. Pinned at 0.05: keeps calm MM
    # inventory ≲ 350.
    mm_qty: Optional[int] = None    # populated from MM_QTY[regime]
    mm_p_edge: float = 4.0          # MM spread (ticks) — CALIBRATED (D48);
                                    # float for surrogate search, rounded at use
    mm_skew: float = 0.05           # inventory skew (parked — HFABM has no skew)

    # ── Clearing tier (D28 — thesis extension of ODD) ────────────────────
    # BCM cast from FT (own-account FT-style); NBCM = pure clearing
    # intermediary (no own position, no LOB). n_bcm_with_clients ≤ n_bcm
    # carry client books (D29). Defaults 0 keep the calibration POP clean.
    n_bcm: int = 0
    n_nbcm: int = 0
    n_bcm_with_clients: int = 0
    n_vt: int = 0              # VolatilityTrader cohort — removed D44
    n_ct: int = 0              # ContTrader cohort — removed D44

    # ── Regime toggle (auto-populates σ_v / fv_csv / mm_qty / qty_max) ───
    stressed: bool = False
    sigma_v: Optional[float] = None
    fv_csv: Optional[str] = None
    sigma_fundamental: Optional[float] = None   # computed in __post_init__

    # ── Order qty (uniform U[qty_min, qty_max], shared FT/MT/ZI). ODD
    # §Stochasticity. Volume scale to empirical ES handled by D50 reporting
    # multiplier, not by per-order qty.
    qty_min: int = 1
    qty_max: Optional[int] = None     # populated from QTY_MAX[regime]

    def __post_init__(self):
        regime = "stressed" if self.stressed else "calm"
        if self.sigma_v is None:
            self.sigma_v = SIGMA_V[regime]
        if self.fv_csv is None:
            self.fv_csv = FV_CSV[regime]
        if self.mm_qty is None:
            self.mm_qty = MM_QTY[regime]
        if self.qty_max is None:
            self.qty_max = QTY_MAX[regime]
        if self.p_zi is None:
            self.p_zi = P_ZI[regime]
        if self.sigma_fundamental is None:
            self.sigma_fundamental = self.ft_sigma_c * self.sigma_v * self.v0


@dataclass
class SimContext:
    """Per-step state passed to every trader's submit_orders. V_t is
    exogenous (loaded from CSV by Simulation). `sigma_t` is the current
    stochastic V_t volatility (D33/D34) — piped into the FT belief width
    so reservation dispersion tracks the vol regime; 0 → fallback to the
    static `params.sigma_v` in agents that consume it. `last_volume` is
    retained for the Stage-4+ CM tier."""
    v: float
    mid_price: float
    tick: int
    traders_by_id: Dict[int, Any]
    last_volume: int = 0       # prior-step transacted volume (Stage 4+)
    sigma_t: float = 0.0       # current SV σ_t (D34); 0 → static fallback
