from __future__ import annotations
from dataclasses import dataclass
from functools import lru_cache
from math import sqrt
from typing import Any, Dict, Optional

# Regime-specific V_t CSV paths — Kalman efficient-price fundamental in the
# `V_smooth` column (+ `sigma_t`), generated by `data/v_kalman.py generate-all`.
FV_CSV = {
    "calm":     "data/fv_calm.csv",
    "stressed": "data/fv_stressed.csv",
}


@lru_cache(maxsize=None)
def day_start_steps(regime: str) -> tuple:
    """Step indices where each RTH session BEGINS in fv_{regime}.csv — index 0 plus
    every date change in the `ts` column (D57). Real ES sessions are ~405 1-min bars
    and vary day to day (down to ~150 on short days), so a fixed 390-bar day is wrong;
    these data-driven boundaries are the single source of truth for the simulator's
    overnight reprice, the calibration's overnight-return exclusion, the daily-return
    slicing, and the notebook's per-day figures. Cached (the fv is static within a run)."""
    import numpy as np
    import pandas as pd
    ts = pd.read_csv(FV_CSV[regime], usecols=["ts"], parse_dates=["ts"])["ts"]
    d = ts.dt.normalize().to_numpy()
    return tuple(int(i) for i in np.flatnonzero(np.r_[True, d[1:] != d[:-1]]))

# Per-regime σ_v: per-step (1-min) log-return std of V_t. Direct fit on the
# 1-min processed ES front-month MID series (data/v_gbm.py calibrate). MT
# also uses this as its reference 1-min return std — by construction the
# empirical 1-min mid log-return std equals σ_v (that is what σ_v is
# calibrated against), so no separate MT_REF dict is needed.
SIGMA_V = {
    "calm":     0.00029732584831326943,
    "stressed": 0.001822674698246824,
}

V0 = {
    "calm":     2463.125,
    "stressed": 3253.875,
}

# MBP-10 geometric placement-depth — diagnostic only (D20). Live limit-
# order placement uses the calibrated log-normal `depth_mean`.
P_ZI = {
    "calm":     0.5430,
    "stressed": 0.3431,
}

# MM top-of-book quote size (D31). Structural — pinned not calibrated;
# `mm_p_edge` is the calibrated MM dial (D48).
MM_QTY = {
    "calm":     2,
    "stressed": 2,
}

# Uniform `U[1, qty_max]` order-size cap (ODD §Stochasticity). D49 reverted
# (Pareto degraded Hill under our linear-impact LOB matching). Flat 10
# matches the ODD baseline; volume scaling to empirical ES is handled by
# the `VOLUME_LOT` relabeling below, not by per-order qty.
QTY_MAX = {
    "calm":     10,
    "stressed": 10,
}

# Institutional-lot relabeling (D50/D53). Each model `qty` unit is read as a block of
# `VOLUME_LOT` ES contracts, set PER REGIME so simulated contract volume matches
# empirical ES per-minute volume (calm ~2,524/min, stressed ~4,979/min). At the D53
# doubled population the sim trades ~84 (calm) / ~81 (stressed) model-lots/min, hence
# VOLUME_LOT ~30 / ~62 (was 45 / 82 at the 50-agent population). ES block-lot scale:
# Eisler-Bouchaud-Kockelkoren (2012). Applied at REPORTING + NOTIONAL + MARGIN only,
# never in the LOB — log-returns, ACFs and Hill are invariant. INTERIM: recompute if
# the final calibration OR the client cash bands shift the realised lots/min (the
# margin cap couples client cash to traded volume).
VOLUME_LOT = {"calm": 30, "stressed": 60}

# CME E-mini ES futures contract multiplier — $50 per index point. USD notional
# per (model lot · price point) = volume_lot · CONTRACT_USD (regime-specific).
CONTRACT_USD = 50.0

# Almgren-Chriss impact coefficients — calibrated from BBO-1m via
# data/impact.py (Hasbrouck 1991 / AC 2000 linear-impact regression).
# NOT currently wired into any agent (AC execution tabled under D10f in
# favour of POV; see ModelParams.mm_pov). Kept here for documentation +
# future re-enable. γ both regimes empirically negative (post-trade price
# reversion dominates at K=30 min, Hasbrouck 1991 / BMP 2002 transient-only
# finding) → floored at 0.
ETA_TEMP = {
    "calm":     1.5094e-4,
    "stressed": 7.0064e-4,
}
GAMMA_PERM = {
    "calm":     0.0,   # raw β_perm = -1.17e-5; transient-only regime
    "stressed": 0.0,   # raw β_perm = -1.38e-4; transient-only regime
}
# Almgren-Chriss liquidation (Stage C — distressed CM fire-sale + CCP default
# liquidation). Slices a position over AC_HORIZON minutes; the temporary impact
# is endogenous (the LOB market orders walk the book); the permanent impact is
# GAMMA_PERM (≈0 empirically). FIRE_SALE_URGENCY = κH front-loads the schedule
# under distress (κH→0 = TWAP, the risk-neutral AC limit; Almgren-Chriss 2000).
AC_LAMBDA = 0.001
AC_HORIZON = 30
FIRE_SALE_URGENCY = 2.0

# ZI rates (zi_alpha limit / zi_mu market / zi_delta cancel) are CALIBRATED
# per regime (D21 — all three entered the loop when the MM was dropped and
# ZI became a primary price driver). The ODD-baseline values (0.15 / 0.025 /
# 0.025) are the ModelParams defaults and the calibration-bound anchors.

# Pin point for FT belief dispersion: σ_fundamental = ft_sigma_c · σ_v · v0
# = one daily V_t std (Chiarella heterogeneous-beliefs at the daily-news
# scale; ABIDES ValueAgent precedent). Calibrating ft_sigma_c was tried and
# landed near √(390·5) (one weekly std); the structural pin removes a
# calibrated parameter at negligible cost (FT belief dispersion is a design
# choice, not a market observable).
FT_SIGMA_C_DEFAULT = sqrt(390.0)

# Calibrated behavioural parameters per regime — the single source the simulator
# entry points (run_simulation.py, analysis_long_run.py) read. RE-COPY after each
# calibration: theta_stage2 from output/calibrated_params.json (surrogate) or the
# optimum in output/calibrated_params_grid.json (grid). Regime-specific loop: calm
# 3-d {ft_sigma_c, zi_alpha, zi_delta}; stressed 4-d {+ p_zi}. zi_mu is pinned at
# the CST-2008 0.025 baseline (ablation C6); calm p_zi stays at the L2 P_ZI value
# (omitted here -> ModelParams default), stressed p_zi is calibrated.
#
# SURROGATE-assisted SMM optima (theta_stage2) on the D57 data-driven-session fundamentals
# (calibrate.py run; XGB-Chiarella surrogate, HFABM 2-stage; overnight returns excluded at the
# real ≈405-bar boundaries). Validated D: calm 42.9 (kurt 5.5, Hill 2.98 vs empirical 2.96;
# residual is mostly KS+ACF2), stressed 12.9 (kurt 119, Hill 2.96 vs empirical 3.18). Surrogate
# held-out R²≈0.79-0.80 both regimes. INTERIM (short pre-meeting budget: n_lhs=36, n_runs=2,
# 1 refine round of 12, 8 stage-2; output/calibrated_params.json): the full grid (the
# easy-to-defend headline) and a thesis-resolution surrogate are still to be re-run — re-copy the
# chosen optimum here once done.
CALIBRATED = {
    "calm": dict(
        ft_sigma_c=0.86608, zi_alpha=0.39996, zi_mu=0.025, zi_delta=0.48260,
    ),
    "stressed": dict(
        ft_sigma_c=0.51910, zi_alpha=0.33092, zi_mu=0.025, zi_delta=0.32996, p_zi=0.18036,
    ),
}


# ── Clearing-tier constants (D28) ────────────────────────────────────────────
# Clearing-member initialisation (ODD §Initialization). Cash is inert (it
# does not gate FT/BCM order submission), so the regulatory-scale BCM/NBCM
# cash does not affect price formation or the calibration.
CCP_CASH = 7_500_000_000            # CCP prefunded resources / SITG capacity — LCH
                                    # SwapClear default-fund cap ~£6B (~$7.5B); supersedes
                                    # the ODD FTSE-scale $10M (it could not fund the SITG)
# Loss-absorbing capital ~ FCM adjusted net capital (CFTC monthly FCM financial data).
BCM_CASH_RANGE = (5e9, 1e10)        # bank-FCM scale (JPM/GS-class); matches ODD U[5B,10B]
NBCM_CASH_RANGE = (5e7, 1e9)        # non-bank FCM adjusted net capital, UNIFORM $50M-$1B —
                                    # spans the CFTC FCM financial data (Apr 2026) non-bank range:
                                    # small clearing FCMs (Dorman/GH/Nanhua/Phillip ~$30-140M) up to
                                    # Marex/Clear Street/ABN AMRO (~$0.8-0.9B). The small end is where
                                    # a concentrated client-default cluster can topple the CM.

# Client (cleared end-user) loss-absorbing capital, by entity type (D52 — client
# clearing). FT = asset managers (largest books -> largest capital), MT = CTA /
# trend institutions, ZI = smaller noise accounts. Client positions are bounded by
# margin capacity (initial margin <= free cash -> exposure <= 5x cash), so cash sets
# the position scale; the bands are tuned so the 8% capital floor freezes clients and
# defaults a subset under STRESS but not in calm (a margin-capped client sits near a
# 20% ratio and defaults only on a ~20% adverse mark — a stressed-regime move).
FT_CLIENT_CASH = (1.0e8, 5.0e8)     # asset-manager scale
MT_CLIENT_CASH = (3.0e7, 1.5e8)     # CTA / trend-institution scale
ZI_CLIENT_CASH = (6.0e7, 1.5e8)     # noise accounts, $60-150M (D53b). ZI inventory random-walks
                                    # but ~cancels on average (mean ≈ 0, ~50/50 long/short); cash set
                                    # so only the unlucky drifters default under stress (≈2 ZI defaults
                                    # vs 8 at $50-100M), keeping client defaults modest but non-zero.

# Client-book concentration (D53c). Each client-carrying CM holds a heterogeneous
# number of clients in this range, and the LARGER CMs (by cash) carry MORE clients
# (bigger FCMs clear bigger books). Skewed book sizes are the client-clearing
# concentration study lever (the cross-member contagion channel — H1/H4).
CLIENT_BOOK_RANGE = (5, 15)

# CCP / clearing-tier calibration — ODD §Calibration table. These pin the
# margin, default-fund and waterfall mechanics built in the LATER stages;
# none is a free (SMM-calibrated) parameter — each is a regulatory / ODD
# constant. Listed here as the single source; wired in stage by stage.
CCP_CALIBRATION = dict(
    im_percent=0.20,        # FIXED broker HOUSE margin — the client POSITION cap only
                            # (D55): clients post 20% of notional, ~5x leverage, the
                            # conservative house multiple over the exchange minimum (FCMs
                            # impose house margin above the CME minimum). The CCP/exchange
                            # initial margin actually CALLED is procyclical VaR/SPAN via
                            # globals.im_fraction(sigma_t); im_percent is NOT that margin.
    mm_percent=0.95,        # maintenance-margin threshold — CME methodology
    df_percent=0.20,        # DEPRECATED (D55) — flat DF haircut superseded by the cover-2
                            # SLOIM (recompute_default_fund); kept for back-compat only.
    df_buffer=0.10,         # DF buffer on the cover-2 SLOIM — Euronext Clearing module A9
                            # §3 (Total DF = cover-2 SLOIM x (1 + 10%))
    ex_df_ratio=0.10,       # exchange skin-in-the-game — EMIR Art. 45
    cover_number=2,         # cover-2 — EMIR / Dodd-Frank; Euronext A9 §3 (two most
                            # exposed banking groups, extreme-but-plausible)
    recovery_rate=0.60,     # auctioned-position recovery — CPMI-IOSCO 2017
    cap_ratio_floor=0.08,   # CM capital floor — CFTC Reg 1.17 (D55): adjusted net capital
                            # >= 8% of risk maintenance margin, i.e. cash/IM >= 0.08
                            # (was cash/notional on a Basel reading; the FCM net-capital
                            # rule is on RISK MARGIN, not gross client notional)
    margin_interval=60,     # variation-margin cadence (hourly) — ODD §Scales
    df_interval=390,        # default-fund recalculation — one thesis RTH day
)                           # (ODD uses 510; the thesis RTH day is 390 — D28)


# ── Margin methodology (D55) — procyclical VaR/SPAN initial margin ────────────
# For a single linear futures contract SPAN scanning risk == parametric VaR, so
# the CCP initial margin is a fraction of notional set by a VaR scan: z-quantile
# of the daily return over the margin period of risk (MPOR), floored by an
# anti-procyclicality (APC) floor anchored to the real CME ES margin. The σ fed in
# is the REGIME 1-min return std (params.sigma_v = SIGMA_V[regime]) scaled to a
# daily std via sqrt(390) — a daily-reset CCP margin, not the per-minute Kalman SV
# `sigma_t` (which is a microstructure-noise scale for FT beliefs and does not
# separate the regimes). IM reverts to the APC floor in calm (~6%) and rises in the
# stressed regime (~12%) — the procyclical channel. Simulation passes params.sigma_v.
#   IM_CONF_Z     99% one-tailed normal — EMIR Art. 41 (>=99%, 2-day ETD), CME SPAN
#   IM_MPOR_DAYS  margin period of risk — 2 business days for exchange-traded futures
#   IM_FLOOR      APC floor ~ CME ES maintenance margin / notional (~6%); EMIR Art. 28
#                 RTS APC option (long-run floor)
#   DF_STRESS_Z   ~99.87% — DF scenario beyond the IM confidence (extreme-but-plausible)
#   DF_STRESS_FLOOR  historical extreme-but-plausible 2-day ES move (2008 / COVID
#                    2020-03 scale) — Euronext A9 §2.1 stress scenarios
TRADING_MINUTES_PER_DAY = 390
IM_CONF_Z = 2.326
IM_MPOR_DAYS = 2
IM_FLOOR = 0.06
DF_STRESS_Z = 3.0
DF_STRESS_FLOOR = 0.15

# House/prop-book risk limit for a banking CM's OWN account (D55). A clearing
# member is primarily an intermediary; its house desk runs under a VaR limit, not
# the unbounded fundamental-trader accumulation that compounds to many ×capital in a
# trend. Cap own notional so its 99%/1-day VaR ≤ HOUSE_VAR_BUDGET · capital (Basel
# FRTB / prop-desk practice): |own notional| ≤ β·cash/(z·σ_daily). Procyclical via the
# regime σ — loose in calm (never binds on a flat day), tight in the stressed/crash
# regime (~0.6×cash), which also makes it a deleveraging-in-stress channel.
HOUSE_VAR_BUDGET = 0.05


def im_fraction(sigma_t: float) -> float:
    """Procyclical CCP initial-margin fraction (of notional), D55. VaR/SPAN scan:
    z * sigma_daily * sqrt(MPOR), with sigma_daily = sigma_t(per-min) * sqrt(390),
    floored at IM_FLOOR (anti-procyclicality). sigma_t<=0 falls back to the floor."""
    s = sigma_t if (sigma_t == sigma_t and sigma_t > 0.0) else 0.0
    sigma_daily = s * sqrt(TRADING_MINUTES_PER_DAY)
    var = IM_CONF_Z * sigma_daily * sqrt(IM_MPOR_DAYS)
    return max(IM_FLOOR, var)


def df_stress_move(sigma_t: float) -> float:
    """Extreme-but-plausible stress price move (fraction) for the cover-2 SLOIM
    default fund (D55) — the larger of a ~99.87% VaR move over the MPOR and the
    historical 2-day ES extreme floor (Euronext A9 §2.1). Always >= im_fraction,
    so SLOIM = (df_stress_move - im_fraction) * notional is non-negative."""
    s = sigma_t if (sigma_t == sigma_t and sigma_t > 0.0) else 0.0
    sigma_daily = s * sqrt(TRADING_MINUTES_PER_DAY)
    return max(DF_STRESS_FLOOR, DF_STRESS_Z * sigma_daily * sqrt(IM_MPOR_DAYS))


@dataclass
class ModelParams:
    # ── Populations (50 LOB + clearing tier) ──────────────────────────────
    n_fundamental: int
    n_momentum: int            # MT short-horizon (per-agent λ = params.mt_lambda)
    n_mm: int                  # market maker count (removed from runtime; default 0)
    n_zi: int                  # ZI background flow (Cont-Stoikov 2008)

    # ── Asset / cadence ──────────────────────────────────────────────────
    v0: float
    tick_size: float
    dt_minutes: float          # 1.0 — 1-min ODD-native cadence

    # ── FT (ODD §Agents) ─────────────────────────────────────────────────
    # Replace-on-new (D5d); trades every step (D36 — `ft_alpha=1.0` pinned).
    # No dead-band — persistent z_score supplies heterogeneity. σ_t reaches
    # the LOB via the FT belief width (D34: σ_fund_t = √390·σ_t·v0).
    ft_alpha: float = 1.0
    ft_sigma_c: float = FT_SIGMA_C_DEFAULT
    ft_delta: float = 0.0      # per-resting stochastic cancellation rate (campaign E5;
                               # CST-2008 / Farmer ZI cancel rate). 0.0 = replace-on-new
                               # only (D58 baseline); >0 re-tests the D36-rejected design.

    # ── ZI (Cont-Stoikov 2008) — three Bernoulli rates per step, all CALIBRATED.
    zi_alpha: float = 0.15     # limit-order arrival
    zi_mu: float = 0.025       # market-order arrival
    zi_delta: float = 0.025    # per-resting cancellation — the SOLE order-lifetime
                               # mechanism for ZI now (D58: the ODD §Mech #7 hard TTL
                               # was removed; orders leave only by fill or cancellation)

    # ── MT (single-cohort EWMA chartist, D13f / D44) ──────────────────────
    # Limit-only (D40). Replace-on-new (D5d). EWMA decay per-agent at init
    # (params.mt_lambda); placement k ~ shared LogNormal `_draw_depth`.
    mt_alpha: float = 1.0         # trades every step (D36)
    mt_delta: float = 0.0         # per-resting stochastic cancellation rate (campaign E5;
                                  # CST-2008 / Farmer). 0.0 = replace-on-new only (baseline).
    mt_mu: float = 0.0            # market branch off (D40)
    mt_lambda: float = 0.05       # EWMA decay — pinned (D44)
    mt_lambda_long: float = 0.02  # long-cohort decay (D35); n_momentum_long=0 by default
    n_momentum_long: int = 0      # D43 long cohort dropped
    mt_eps: float = 1e-6          # |M_t| floor — skips EWMA warm-up

    # ── Parked agent params (kept for back-compat; cohorts not active) ───
    vt_qty_base: float = 2.0      # VolatilityTrader (D38, removed D44)
    ct_update_prob: float = 0.05  # ContTrader (D39, removed D44)
    ct_qty: float = 1.0

    # ── Limit-order placement depth (shared ZI + MT) ─────────────────────
    # GEOMETRIC k ~ Geometric(p_zi), data-fit p_zi from MBP-10 (Cont-Stoikov-
    # Talreja 2008; reverts the D20 log-normal back to the D3 geometric). Dense
    # at the mid (mode k=1) → thick near-mid book → market orders don't walk a
    # sparse book (the kurtosis-amplification fix). p_zi is data-fixed, NOT in
    # the agent loop. depth_mean/depth_sigma parked for back-compat (unused).
    p_zi: Optional[float] = None  # geometric placement param; populated from P_ZI
    depth_sigma: float = 0.3      # parked (log-normal shape — superseded)
    depth_mean: float = 2.5       # parked (log-normal mean — superseded)

    # ── Stage-4+ fire-sale scaffolding (NOT yet wired) ───────────────────
    # POV execution helpers for the deferred BCM/CCP distressed liquidation
    # (Almgren-Thum-Hauptmann-Li 2005). `ac_schedule()` in agents.py + the
    # ETA_TEMP / GAMMA_PERM dicts above carry over directly when wired.
    mm_pov: float = 0.10
    mm_inventory_limit: int = 1000
    mm_inventory_safe: int = 800      # Stage 4+: post-fire-sale target

    # ── MM (fundamental-anchored inventory-skewed quoting — D10g) ────────
    # `mm_qty` regime-derived from MM_QTY dict (top-of-book passive size,
    # structural). `mm_skew` is the inventory-skew coefficient in the MM
    # reservation r = V_t − mm_skew·inventory·tick (Avellaneda-Stoikov
    # 2008). STRUCTURAL — not calibrated (D10c upheld); it has no traction
    # on the return moments (the V_t anchor pins the mid regardless), its
    # only role is bounding MM inventory. Pinned at 0.05: keeps calm MM
    # inventory ≲ 350.
    mm_qty: Optional[int] = None    # populated from MM_QTY[regime]
    mm_p_edge: float = 4.0          # MM spread (ticks) — CALIBRATED (D48);
                                    # float for surrogate search, rounded at use
    mm_skew: float = 0.05           # inventory skew (parked — HFABM has no skew)

    # ── Clearing tier (D28 — thesis extension of ODD) ────────────────────
    # BCM cast from FT (own-account FT-style); NBCM = pure clearing
    # intermediary (no own position, no LOB). n_bcm_with_clients ≤ n_bcm
    # carry client books (D29). Defaults 0 keep the calibration POP clean.
    n_bcm: int = 0
    n_nbcm: int = 0
    n_bcm_with_clients: int = 0
    n_vt: int = 0              # VolatilityTrader cohort — removed D44
    n_ct: int = 0              # ContTrader cohort — removed D44

    # ── Regime toggle (auto-populates σ_v / fv_csv / mm_qty / qty_max) ───
    stressed: bool = False
    sigma_v: Optional[float] = None
    fv_csv: Optional[str] = None
    sigma_fundamental: Optional[float] = None   # computed in __post_init__

    # ── Order qty (uniform U[qty_min, qty_max], shared FT/MT/ZI). ODD
    # §Stochasticity. Volume scale to empirical ES handled by D50 reporting
    # multiplier, not by per-order qty.
    qty_min: int = 1
    qty_max: Optional[int] = None     # populated from QTY_MAX[regime]
    volume_lot: Optional[float] = None  # contracts per lot — from VOLUME_LOT[regime]

    def __post_init__(self):
        regime = "stressed" if self.stressed else "calm"
        if self.sigma_v is None:
            self.sigma_v = SIGMA_V[regime]
        if self.fv_csv is None:
            self.fv_csv = FV_CSV[regime]
        if self.mm_qty is None:
            self.mm_qty = MM_QTY[regime]
        if self.qty_max is None:
            self.qty_max = QTY_MAX[regime]
        if self.p_zi is None:
            self.p_zi = P_ZI[regime]
        if self.volume_lot is None:
            self.volume_lot = VOLUME_LOT[regime]
        if self.sigma_fundamental is None:
            self.sigma_fundamental = self.ft_sigma_c * self.sigma_v * self.v0


@dataclass
class SimContext:
    """Per-step state passed to every trader's submit_orders. V_t is
    exogenous (loaded from CSV by Simulation). `sigma_t` is the current
    stochastic V_t volatility (D33/D34) — piped into the FT belief width
    so reservation dispersion tracks the vol regime; 0 → fallback to the
    static `params.sigma_v` in agents that consume it. `last_volume` is
    retained for the Stage-4+ CM tier."""
    v: float
    mid_price: float
    tick: int
    traders_by_id: Dict[int, Any]
    last_volume: int = 0       # prior-step transacted volume (Stage 4+)
    sigma_t: float = 0.0       # current SV σ_t (D34); 0 → static fallback
