from __future__ import annotations
from dataclasses import dataclass
from functools import lru_cache
from math import sqrt
from typing import Any, Dict, Optional

# Regime-specific V_t CSV paths — Kalman efficient-price fundamental in the
# `V_smooth` column (+ `sigma_t`), generated by `data/v_kalman.py generate-all`.
FV_CSV = {
    "calm":     "data/fv_calm.csv",
    "stressed": "data/fv_stressed.csv",
}


@lru_cache(maxsize=None)
def day_start_steps(regime: str) -> tuple:
    """Step indices where each RTH session begins in fv_{regime}.csv — index 0 plus
    every date change in the `ts` column. Real ES sessions vary in length (~150–405
    1-min bars), so these data-driven boundaries, not a fixed 390-bar day, drive the
    overnight reprice, the overnight-return exclusion, and the daily-return slicing.
    Cached since the fv is static within a run."""
    import numpy as np
    import pandas as pd
    ts = pd.read_csv(FV_CSV[regime], usecols=["ts"], parse_dates=["ts"])["ts"]
    d = ts.dt.normalize().to_numpy()
    return tuple(int(i) for i in np.flatnonzero(np.r_[True, d[1:] != d[:-1]]))

# Per-regime σ_v: per-step (1-min) log-return std of V_t, fit on the 1-min
# processed ES front-month mid series (data/v_gbm.py calibrate). Also serves as
# the MT reference 1-min return std (by construction equal to σ_v).
SIGMA_V = {
    "calm":     0.00029732584831326943,
    "stressed": 0.001822674698246824,
}

V0 = {
    "calm":     2463.125,
    "stressed": 3253.875,
}

# MBP-10 geometric placement-depth p_zi, fit by data/p_zi.py. The shared ZI/MT
# limit placement is k ~ Geometric(p_zi). Calm uses this measured value directly;
# stressed p_zi is calibrated and lives in CALIBRATED.
P_ZI = {
    "calm":     0.5430,
    "stressed": 0.3431,
}

# Uniform `U[1, qty_max]` order-size cap (ODD §Stochasticity). Flat 10 matches the
# ODD baseline; volume scaling to empirical ES is handled by the `VOLUME_LOT`
# relabeling below, not by per-order qty.
QTY_MAX = {
    "calm":     10,
    "stressed": 10,
}

# Institutional-lot relabeling. Each model `qty` unit is read as a block of
# `VOLUME_LOT` ES contracts, set per regime so simulated contract volume matches
# empirical ES per-minute volume (calm ~2,524/min, stressed ~4,979/min). ES block-lot
# scale: Eisler-Bouchaud-Kockelkoren (2012). Applied at reporting, notional and margin
# only, never in the LOB — log-returns, ACFs and Hill are invariant.
VOLUME_LOT = {"calm": 30, "stressed": 60}

# CME E-mini ES futures contract multiplier — $50 per index point. USD notional
# per (model lot · price point) = volume_lot · CONTRACT_USD (regime-specific).
CONTRACT_USD = 50.0

# Almgren-Chriss impact coefficients — calibrated from BBO-1m via
# data/impact.py (Hasbrouck 1991 / AC 2000 linear-impact regression).
# γ is empirically negative in both regimes (post-trade reversion dominates at
# K=30 min, Hasbrouck 1991 / BMP 2002 transient-only finding) → floored at 0.
ETA_TEMP = {
    "calm":     1.5094e-4,
    "stressed": 7.0064e-4,
}
GAMMA_PERM = {
    "calm":     0.0,   # raw β_perm = -1.17e-5; transient-only regime
    "stressed": 0.0,   # raw β_perm = -1.38e-4; transient-only regime
}
# Almgren-Chriss liquidation (distressed CM fire-sale + CCP default liquidation).
# Slices a position over AC_HORIZON minutes; temporary impact is endogenous (LOB
# market orders walk the book), permanent impact is GAMMA_PERM (≈0 empirically).
# FIRE_SALE_URGENCY = κH front-loads the schedule under distress (κH→0 = TWAP, the
# risk-neutral limit; Almgren-Chriss 2000).
AC_HORIZON = 30
FIRE_SALE_URGENCY = 2.0

# Close-out of a defaulted book — split by WHO resolves it:
#
#  CLOSEOUT_MODE — a defaulted MEMBER's book (resolved by the CCP). "transfer" (DEFAULT):
#       the CCP AUCTIONS it to the surviving member with the largest opposing position at
#       CLOSEOUT_RECOVERY; the (1-recovery) haircut goes to the waterfall, no open-market
#       impact. "firesale": CCP open-market Almgren-Chriss disposal (deferred hypothesis).
#       A defaulted DIRECT client (H1 counterfactual, faced by the CCP) is resolved the
#       same way (CCP auction).
#
#  CLIENT_CLOSEOUT — a defaulted tiered CLIENT's book (resolved by its clearing MEMBER).
#       "firesale" (DEFAULT): the member ASSUMES the position and liquidates it OPEN-MARKET
#       via Almgren-Chriss (the member's book-walk is the client-level price-impact channel).
#       "transfer": assign to the member's largest-offsetting client at recovery (no impact).
#       Rationale: only the CCP runs an auction; members liquidate assumed client positions
#       into the market — and a single client's position is small enough that the open-market
#       impact is realistic (unlike a whole member book, which is why members are auctioned).
#
# Real CCP auctions recover close to par on a hedged book (LCH used only ~35% of Lehman's
# IM and no default fund in 2008; BIS Dec-2018; IOSCO PD657), while concentrated/unhedged
# books recover less (Nasdaq 2018). 0.80 is a conservative stressed recovery — more
# conservative than the Lehman outcome, less than the ODD's credit-style 0.60. Sensitivity-test.
CLOSEOUT_MODE = "transfer"
CLIENT_CLOSEOUT = "firesale"
CLOSEOUT_RECOVERY = 0.80

# Capital-ratio deleverage TARGET — a management buffer above cap_ratio_floor (0.08).
# A solvent BCM breaching the 8% floor deleverages (Almgren-Chriss) back to THIS ratio,
# not to the floor itself, so it does not immediately re-breach on the next adverse tick
# (deleveraging to a buffer above the regulatory minimum is standard practice). ~1.5x the
# floor; raise toward 0.15 for a wider cushion. Only the SOLVENT deleverage uses this;
# the DEFAULT close-out is governed by CLOSEOUT_MODE.
CAP_DELEVERAGE_TARGET = 0.12

# Client-margin netting basis for the CM's IM / capital ratio:
#   "gross" (default) — Sum|client_pos|: US/CME gross customer margining (CFTC).
#   "net"             — |Sum client_pos|: EU net-omnibus — offsetting client positions
#                       cancel, lowering the CM's IM and mitigating capital-ratio stop-out
#                       (the Duffie-Zhu 2011 netting benefit / the H1 tiering value).
# VM and the cover-2 default fund already use the NET book (book_position); this toggle
# changes only the margin/capital basis. A clean gross-vs-net comparison axis.
CLIENT_MARGIN_NETTING = "gross"

# ZI rates (zi_alpha limit / zi_mu market / zi_delta cancel) are calibrated per
# regime. The ODD-baseline values (0.15 / 0.025 / 0.025) are the ModelParams
# defaults and the calibration-bound anchors.

# Default for the FT belief-width scale (one daily V_t std). ft_sigma_c is
# calibrated per regime — the dominant tail lever — and every entry point overrides
# this via CALIBRATED, so the default only matters for ad-hoc ModelParams builds.
FT_SIGMA_C_DEFAULT = sqrt(390.0)

# Calibrated behavioural parameters per regime — the single source the simulator
# entry points (run_simulation.py, analysis_long_run.py) read. Grid-search optima
# (calm 4-d, stressed 5-d; see calibrate.py). Re-copy after each calibration:
# theta_stage2 from output/calibrated_params.json (surrogate) or the optimum in
# output/calibrated_params_grid.json (grid). Calm p_zi stays at the L2 P_ZI value
# (omitted here -> ModelParams default); stressed p_zi is calibrated.
CALIBRATED = {
    # D66 V_t-form relock grid optima (output/relock/grid_*.json, seed 42).
    # Calm ft_sigma_c is weakly identified: D is flat (~43.9-44.5) over 0.5-0.95,
    # and the three methods disagree (grid 0.65 / fresh-seed 0.50 / surrogate 1.09)
    # while agreeing on zi_alpha ~0.38 (the identified calm lever). Stressed is
    # unchanged from the prior lock (ft_sigma_c pinned to the 0.25 box floor; only
    # the weakly-identified zi_mu wanders -- fresh-seed prefers 0.104).
    "calm": dict(
        ft_sigma_c=0.65, zi_alpha=0.38, zi_mu=0.08125, zi_delta=0.02,
    ),
    "stressed": dict(
        ft_sigma_c=0.25, zi_alpha=0.32, zi_mu=0.05833, zi_delta=0.02, p_zi=0.18,
    ),
}


# ── Clearing-tier constants ──────────────────────────────────────────────────
# Clearing-member initialisation (ODD §Initialization). Cash is inert (it
# does not gate FT/BCM order submission), so the regulatory-scale BCM/NBCM
# cash does not affect price formation or the calibration.
CCP_CASH = 1_500_000_000            # CCP OWN capital — the SITG source and the Level-5
                                    # backstop. ~$1-2B is a major CCP's own equity/dedicated
                                    # resources (vs TOTAL prefunded DF ~$9-10B = SITG + member
                                    # fund, which is NOT the CCP's own cash). At ~$1.5B the L5
                                    # backstop can be exhausted under extreme stress, so CCP
                                    # insolvency is reachable in the deferred reverse-stress /
                                    # fire-sale hypotheses, while staying inert at actual severity
                                    # (L5 never reached; the SITG cap below does not bind). NOTE
                                    # this is NOT the SITG: SITG = ex_df_ratio (3%) of the cover-2
                                    # fund (~$20-30M), set in CCP_CALIBRATION below.
# Loss-absorbing capital ~ FCM adjusted net capital (CFTC monthly FCM financial data).
BCM_CASH_RANGE = (5e9, 1e10)        # bank-FCM scale (JPM/GS-class); matches ODD U[5B,10B]
NBCM_CASH_RANGE = (5e7, 1e9)        # non-bank FCM adjusted net capital, UNIFORM $50M-$1B —
                                    # spans the CFTC FCM financial data (Apr 2026) non-bank range:
                                    # small clearing FCMs (Dorman/GH/Nanhua/Phillip ~$30-140M) up to
                                    # Marex/Clear Street/ABN AMRO (~$0.8-0.9B). The small end is where
                                    # a concentrated client-default cluster can topple the CM.

# Client (cleared end-user) loss-absorbing capital, by entity type. FT = asset
# managers (largest books -> largest capital), MT = CTA / trend institutions, ZI =
# smaller noise accounts. Client positions are bounded by margin capacity (initial
# margin <= free cash -> exposure <= 5x cash), so cash sets the position scale; the
# bands are tuned so the 8% capital floor freezes clients and defaults a subset under
# stress but not in calm (a margin-capped client sits near a 20% ratio and defaults
# only on a ~20% adverse mark — a stressed-regime move).
FT_CLIENT_CASH = (1.0e8, 5.0e8)     # asset-manager scale
MT_CLIENT_CASH = (3.0e7, 1.5e8)     # CTA / trend-institution scale
ZI_CLIENT_CASH = (6.0e7, 1.5e8)     # noise accounts, $60-150M. ZI inventory random-walks
                                    # but ~cancels on average (mean ≈ 0, ~50/50 long/short); cash set
                                    # so only the unlucky drifters default under stress, keeping
                                    # client defaults modest but non-zero.

# Client-book concentration. Each client-carrying CM holds a heterogeneous number of
# clients in this range, and the larger CMs (by cash) carry more clients (bigger FCMs
# clear bigger books). Skewed book sizes are the concentration study lever (the
# cross-member contagion channel — H1/H4).
CLIENT_BOOK_RANGE = (5, 15)

# H4/L4 lever (run_simulation.build_clearing_tier). Concentrate the most directional
# (highest-z, persistent-long) FT clients on the single most fragile (smallest-cash) NBCM
# — pinned to the cash floor — so its NET client book is one-sided and a down-gap can
# exceed its cash, firing the client->NBCM->survivor-mutualisation (waterfall L4) channel.
# The 5x GROSS margin cap keeps net-cancelling books (e.g. ZI) small, so size heterogeneity
# alone does not reach L4 (the documented dormancy); directional concentration is the lever.
# Set True to enable. NOTE (verified): with cover-2 SLOIM sizing, concentrating notional
# on the fragile NBCM also ENLARGES the fund (it becomes a top-2 member), and the early
# fragile-NBCM exit + the freeze/stop-out that bounds the directional book mean the deficit
# is absorbed LOW in the waterfall (L1), not at L3/L4 — so this lever does NOT reach deeper
# mutualisation and is left OFF by default. L4 dormancy is partly STRUCTURAL to cover-2
# (the fund is sized to cover the 2 largest, so a single member's default is usually covered
# by L1-L3); the reverse-stress multiplier c is the intended lever for breaching the fund.
CONCENTRATE_FT_ON_FRAGILE_NBCM = False
FRAGILE_CLIENT_COUNT = 8

# CCP / clearing-tier calibration — ODD §Calibration table. These pin the margin,
# default-fund and waterfall mechanics; none is a free (SMM-calibrated) parameter —
# each is a regulatory / ODD constant.
CCP_CALIBRATION = dict(
    im_percent=0.20,        # fixed broker house margin — the client position cap only:
                            # clients post 20% of notional (~5x leverage), the conservative
                            # house multiple over the exchange minimum. The initial margin
                            # actually called is procyclical VaR/SPAN via im_fraction(sigma_t);
                            # im_percent is NOT that margin.
    mm_percent=0.95,        # maintenance-margin threshold — CME methodology
    df_buffer=0.10,         # DF buffer on the cover-2 SLOIM — Euronext Clearing module A9
                            # §3 (Total DF = cover-2 SLOIM x (1 + 10%))
    ex_df_ratio=0.03,       # exchange skin-in-the-game as a SHARE OF THE FUND. Real SITG
                            # is ~1-4% of the prefunded fund (CME ES $100M/$9.4B ~2.7%,
                            # ICE Europe ~2%; Clarus CCP-disclosure data). NB EMIR Art. 45
                            # mandates dedicated own resources = 25% of the CCP's CAPITAL
                            # (a small absolute number), NOT 10% of the fund — the prior
                            # 0.10 conflated the two; 0.03 is the empirical %-of-fund.
    cover_number=2,         # cover-2 — EMIR / Dodd-Frank; Euronext A9 §3 (two most
                            # exposed banking groups, extreme-but-plausible)
    cap_ratio_floor=0.08,   # CM capital floor — CFTC Reg 1.17: adjusted net capital
                            # >= 8% of risk maintenance margin, i.e. cash/IM >= 0.08
                            # (on risk margin, not gross client notional)
    margin_interval=60,     # variation-margin cadence (hourly) — ODD §Scales
    df_interval=390,        # default-fund recalculation — one RTH day
)


# ── Margin methodology — procyclical VaR/SPAN initial margin ──────────────────
# For a single linear futures contract SPAN scanning risk == parametric VaR, so the
# CCP initial margin is a fraction of notional set by a VaR scan: z-quantile of the
# daily return over the margin period of risk (MPOR), floored by an anti-procyclicality
# (APC) floor anchored to the real CME ES margin. The σ fed in is a 1-min return std
# scaled to daily via sqrt(390). IM reverts to the APC floor in calm (~6%) and rises in
# the stressed regime (~12%) — the procyclical channel.
#   IM_CONF_Z     99% one-tailed normal — EMIR Art. 41 (>=99%, 2-day ETD), CME SPAN
#   IM_MPOR_DAYS  margin period of risk — 2 business days for exchange-traded futures
#   IM_FLOOR      APC floor ~ CME ES maintenance margin / notional (~6%); EMIR Art. 28
#                 RTS APC option (long-run floor)
#   DF_STRESS_Z   ~99.87% — DF scenario beyond the IM confidence (extreme-but-plausible)
#   DF_STRESS_FLOOR  historical extreme-but-plausible 2-day ES move (2008 / COVID
#                    2020-03 scale) — Euronext A9 §2.1 stress scenarios
TRADING_MINUTES_PER_DAY = 390
IM_CONF_Z = 2.326
IM_MPOR_DAYS = 2
IM_FLOOR = 0.06
DF_STRESS_Z = 3.0
DF_STRESS_FLOOR = 0.15

# IM_CAP — hard upper bound on the IM fraction (physical / APC ceiling). Real CCPs cap
# and smooth margin changes, and a single 2-day 99% move never approaches 100% of
# notional. Without a cap the reactive EWMA can drive IM above notional in deep stress
# as the open book shrinks (an artifact); 0.30 bounds that while leaving the realistic
# reactive range (~6-25%) untouched. (Calm IM ~6-9%, stressed ~12-25%, all below the cap.)
IM_CAP = 0.30

# DF_STRESS_CAP — companion ceiling on the cover-2 stress move. The SLOIM coefficient is
# (df_stress_move - im_frac); capping IM but not the stress move would let the coefficient
# (and the fund) balloon in deep stress (DF -> ~$16B at 4x COVID, vs real CME ~$9B). A
# 2-day extreme-but-plausible ES move ceiling (~2008/COVID scale) bounds it; it only binds
# at high reverse-stress c (calm/COVID stress_move ~15% << cap, so normal behaviour is
# unchanged). Keeps the fund a realistic size and lets a right-sized fund be breached at c.
DF_STRESS_CAP = 0.35

# DF_DECOUPLE_IM — H2 robustness lever. The cover-2 SLOIM nets posted IM out of the
# stress loss (SLOIM = (stress_move - im_frac)*notional), so a higher reactive IM
# mechanically SHRINKS the fund (model.md §6.2). That is faithful stress-loss-over-IM
# accounting, so the realistic default is False; but it couples fund size to the IM mode
# and confounds the H2 mutualisation result. Set True to size the fund on a FIXED
# reference IM (IM_FLOOR), independent of the live IM mode, isolating the pure
# procyclicality channel (run both arms and report the pair).
DF_DECOUPLE_IM = False

# ── H2 margin-regime experiment ───────────────────────────────────────────────
# IM_MODE selects how the CCP margin fraction is driven (flip at runtime in
# experiment scripts, like CALIBRATED):
#   "reactive" — VaR on an EWMA of realised 1-min sim returns (RiskMetrics-style
#                rolling estimator; the realistic baseline — CME raised ES IM six
#                times over ~3 weeks in Mar-2020), read at each margin cycle.
#   "static"   — regime-constant sigma_v (two-point procyclicality across regimes).
#   "flat"     — fixed fraction IM_FLAT_FRAC, no vol response (H2 comparators:
#                0.05 flat-low vs 0.12 through-the-cycle — EMIR Art. 28 APC
#                buffer alternatives; BCBS-CPMI-IOSCO 2022 margin review).
# The EWMA half-life is 2 RTH days of 1-min bars; overnight gaps are excluded
# from the estimator (intraday convention, consistent with SIGMA_V) while gap
# risk stays covered by the sqrt(MPOR) scaling.
IM_MODE = "reactive"
IM_FLAT_FRAC = 0.05
IM_VOL_HALFLIFE = 2 * TRADING_MINUTES_PER_DAY

# ── Open-disorder sensitivity (overnight-gap experiment) ──────────────────────
# At a session boundary the book is repriced to the gapped V_t and each trader's
# intraday price memory is re-anchored to the new open, so the overnight gap is not
# read as a one-step intraday return (the clean open). Set False to leave price memory
# at the prior close: the gap is then seen as a return — the MomentumTrader chases it
# and the open is disorderly — which isolates whether a disorderly open changes
# client/CM contagion vs the clean reprice. The reprice itself and the reactive-IM
# estimator are unaffected either way.
REANCHOR_ON_GAP = True

# House/prop-book risk limit for a banking CM's own account. A clearing member is
# primarily an intermediary; its house desk runs under a VaR limit, not unbounded
# accumulation. Cap own notional so its 99%/1-day VaR ≤ HOUSE_VAR_BUDGET · capital
# (Basel FRTB / prop-desk practice): |own notional| ≤ β·cash/(z·σ_daily). Procyclical
# via the regime σ — loose in calm, tight in the stressed regime (~0.6×cash), so it
# doubles as a deleveraging-in-stress channel.
HOUSE_VAR_BUDGET = 0.05

# Capital-ratio denominator / IM accounting.
#   "im"            — legacy: kappa = cash / IM (CFTC Reg 1.17, capital over risk margin).
#                     IM is NOT escrowed; the procyclicality channel runs through the
#                     denominator (reactive IM rises in a crash -> kappa falls).
#   "free_position" — IM is escrowed at the CCP (it drains cash), so the ratio is
#                     UNENCUMBERED capital over cleared exposure:
#                       kappa = (cash - IM) / exposure = cash/exposure - im_frac.
#                     Net-position leverage form (ODD/Basel; mirrors |tradePosition|).
#                     The margin regime now transmits through the NUMERATOR (a funding-
#                     liquidity squeeze: reactive IM locks more cash in a crash -> kappa
#                     falls), and leverage is procyclically bounded at cash/(floor+im_frac)
#                     (~7x calm, ~2.6x stress), which makes a separate VaR cap redundant.
CAP_RATIO_MODE = "im"

# Physical IM escrow. When True, initial margin is moved as real cash to the CCP's
# im_account each cycle (returned as the position shrinks, seized first on default):
# members post on their OWN book, clients post their OWN procyclical IM via their CM.
# A member/client that cannot fund the call defaults on LIQUIDITY. With escrow the
# capital ratio is cash/exposure (cash is already net of posted IM), so leverage is
# self-bounded at cash/(floor+im_frac) and the procyclicality channel runs through the
# cash numerator (a funding squeeze) rather than the denominator.
IM_ESCROW = True

# Static own-book leverage cap, replacing the sigma-dependent VaR cap when > 0:
# |own notional| <= POSITION_LIMIT_X * cash. Applied ONLY to client-clearing BCMs
# (own-account-only BCMs run uncapped, bounded by the capital ratio). No volatility
# input — a flat gross-leverage limit. 0.0 disables it (fall back to HOUSE_VAR_BUDGET).
POSITION_LIMIT_X = 2.0
# Scope of the static position limit: True = client-clearing BCMs only (own-account-only
# BCMs run uncapped); False = all banking CMs. Set False: the sweep showed an uncapped
# own-account BCM balloons to ~7x and blows the waterfall to L4 (a mutualised artifact).
POSITION_LIMIT_CLIENTS_ONLY = False


def im_fraction(sigma_t: float) -> float:
    """CCP initial-margin fraction (of notional). VaR/SPAN scan:
    z * sigma_daily * sqrt(MPOR), with sigma_daily = sigma_t(per-min) * sqrt(390),
    floored at IM_FLOOR (anti-procyclicality) and capped at IM_CAP (physical/APC
    ceiling). sigma_t<=0 falls back to the floor. Under IM_MODE == "flat" a fixed
    IM_FLAT_FRAC applies with no volatility response (the sigma argument is ignored)."""
    if IM_MODE == "flat":
        return min(IM_CAP, IM_FLAT_FRAC)
    s = sigma_t if (sigma_t == sigma_t and sigma_t > 0.0) else 0.0
    sigma_daily = s * sqrt(TRADING_MINUTES_PER_DAY)
    var = IM_CONF_Z * sigma_daily * sqrt(IM_MPOR_DAYS)
    return min(IM_CAP, max(IM_FLOOR, var))


def df_stress_move(sigma_t: float) -> float:
    """Extreme-but-plausible stress price move (fraction) for the cover-2 SLOIM
    default fund — the larger of a ~99.87% VaR move over the MPOR and the historical
    2-day ES extreme floor (Euronext A9 §2.1), capped at DF_STRESS_CAP so the IM cap does
    not inflate the SLOIM coefficient in deep stress. Always >= im_fraction in normal use,
    so SLOIM = (df_stress_move - im_fraction) * notional is non-negative."""
    s = sigma_t if (sigma_t == sigma_t and sigma_t > 0.0) else 0.0
    sigma_daily = s * sqrt(TRADING_MINUTES_PER_DAY)
    return min(DF_STRESS_CAP,
               max(DF_STRESS_FLOOR, DF_STRESS_Z * sigma_daily * sqrt(IM_MPOR_DAYS)))


@dataclass
class ModelParams:
    # ── Populations (100 LOB + clearing tier) ─────────────────────────────
    n_fundamental: int
    n_momentum: int            # MT short-horizon (per-agent λ = params.mt_lambda)
    n_zi: int                  # ZI background flow (Cont-Stoikov 2008)

    # ── Asset / cadence ──────────────────────────────────────────────────
    v0: float
    tick_size: float
    dt_minutes: float          # 1.0 — 1-min ODD-native cadence

    # ── FT (ODD §Agents) ─────────────────────────────────────────────────
    # Replace-on-new; trades every step (`ft_alpha=1.0`). No dead-band — the
    # persistent z_score supplies heterogeneity. σ_t (EWMA realised vol of V_t)
    # reaches the LOB via the FT reservation R = V_t·(1 + z·ft_sigma_c·σ_t).
    ft_alpha: float = 1.0
    ft_sigma_c: float = FT_SIGMA_C_DEFAULT
    ft_delta: float = 0.0      # per-resting stochastic cancellation rate (CST-2008 /
                               # Farmer ZI cancel rate). 0.0 = replace-on-new only.

    # ── ZI (Cont-Stoikov 2008) — three Bernoulli rates per step, all calibrated.
    zi_alpha: float = 0.15     # limit-order arrival
    zi_mu: float = 0.025       # market-order arrival
    zi_delta: float = 0.025    # per-resting cancellation — the sole order-lifetime
                               # mechanism for ZI (orders leave only by fill or cancel)

    # ── MT (single-cohort EWMA chartist) ──────────────────────────────────
    # Limit-only. Replace-on-new. EWMA decay per-agent at init (params.mt_lambda);
    # placement k ~ shared geometric `_draw_depth`.
    mt_alpha: float = 1.0         # trades every step
    mt_delta: float = 0.0         # per-resting stochastic cancellation rate (CST-2008 /
                                  # Farmer). 0.0 = replace-on-new only.
    mt_mu: float = 0.0            # market branch off
    mt_lambda: float = 0.05       # EWMA decay — pinned
    mt_eps: float = 1e-6          # |M_t| floor — skips EWMA warm-up

    # ── Limit-order placement depth (shared ZI + MT) ─────────────────────
    # k ~ Geometric(p_zi), data-fit p_zi from MBP-10. Dense at the mid (mode k=1)
    # → thick near-mid book → market orders don't walk a sparse book. Calm p_zi is
    # data-fixed; stressed p_zi is calibrated.
    p_zi: Optional[float] = None  # geometric placement param; populated from P_ZI

    # ── Clearing tier (thesis extension of ODD) ──────────────────────────
    # BCM cast from FT (own-account FT-style); NBCM = pure clearing intermediary
    # (no own position, no LOB). n_bcm_with_clients ≤ n_bcm carry client books.
    # Defaults 0 keep the calibration population clean.
    n_bcm: int = 0
    n_nbcm: int = 0
    n_bcm_with_clients: int = 0

    # ── Regime toggle (auto-populates σ_v / fv_csv / mm_qty / qty_max) ───
    stressed: bool = False
    sigma_v: Optional[float] = None
    fv_csv: Optional[str] = None
    sigma_fundamental: Optional[float] = None   # computed in __post_init__

    # ── Order qty (uniform U[qty_min, qty_max], shared FT/MT/ZI). ODD
    # §Stochasticity. Volume scale to empirical ES handled by the reporting
    # multiplier, not by per-order qty.
    qty_min: int = 1
    qty_max: Optional[int] = None     # populated from QTY_MAX[regime]
    volume_lot: Optional[float] = None  # contracts per lot — from VOLUME_LOT[regime]

    def __post_init__(self):
        regime = "stressed" if self.stressed else "calm"
        if self.sigma_v is None:
            self.sigma_v = SIGMA_V[regime]
        if self.fv_csv is None:
            self.fv_csv = FV_CSV[regime]
        if self.qty_max is None:
            self.qty_max = QTY_MAX[regime]
        if self.p_zi is None:
            self.p_zi = P_ZI[regime]
        if self.volume_lot is None:
            self.volume_lot = VOLUME_LOT[regime]
        if self.sigma_fundamental is None:
            self.sigma_fundamental = self.ft_sigma_c * self.sigma_v * self.v0


@dataclass
class SimContext:
    """Per-step state passed to every trader's submit_orders. V_t is exogenous
    (loaded from CSV by Simulation). `sigma_t` is the current stochastic V_t
    volatility — piped into the FT belief width so reservation dispersion tracks
    the vol regime; 0 → fallback to the static `params.sigma_v` in agents that
    consume it. `last_volume` is retained for the CM tier."""
    v: float
    mid_price: float
    tick: int
    traders_by_id: Dict[int, Any]
    last_volume: int = 0       # prior-step transacted volume
    sigma_t: float = 0.0       # current SV σ_t; 0 → static fallback
